### ISSUE TITLE
Some Object Names Clash with Abstractions from Libraries

### ISSUE THREAD

**Issue by Enkerli** [algomusic/Live-Coding-Toolkit-for-Pure-Data#1]
Trying the examples in PlugData, I noticed that several of these abstractions use the same names as those found in cyclone or ELSE, including `cycle`. As a test, I’ve prefixed all calls to abstractions (with `lct/`) and added the `Live-Coding-Toolkit-for-Pure-Data-main` as `lct` to `~/Documents/plugdata/Abstractions`, adding that to the search path. All Examples now work.

While it might have been enough to change only some names, I find it useful to group these toolkit items under `lct/` (e.g. `[lct/fm~]`).
![Capture d’écran, le 2024-05-03 à 15 42 34](https://github.com/algomusic/Live-Coding-Toolkit-for-Pure-Data/assets/327544/f2a37a94-5828-4b12-8d0a-5663300ad38f)

I could (should?) do some PRs about this…

**Comment by algomusic** [comment]
A known issue, but thanks for the suggestion to use prefixes. I've added this suggestion into the readme.

**Comment by Enkerli** [comment]
AFAICT, these are the object names which need to be changed in the Examples (all occurrences):

- cycle
- direct
- drums~
- echo~
- midi
- out~
- periodic
- polysynth~
- quant
- ramp
- rand
- synth~
- tempo

(Other abstractions aren’t called in those example patches.)

Also, if I’m not mistaken, calls to all abstractions need to be replaced in help files and in some abstractions (say, `[polysample~]`, which calls `[sample-wrapper]`).
