### ISSUE TITLE
Failed Connections in Examples

### ISSUE THREAD

**Issue by Enkerli** [algomusic/Live-Coding-Toolkit-for-Pure-Data#2]
In both PurrData (2.19.3) and Plugdata (0.9.0 beta), I’m getting the following errors when trying the Examples:

```
simple-cycle-midi.pd 3 2 1 5 (canvas->canvas) connection failed
simple-cycle-audio.pd 2 2 1 5 (canvas->canvas) connection failed
midi-random-chords.pd 10 2 1 5 (canvas->canvas) connection failed
midi-melodic-function.pd 2 0 7 5 (bng->canvas) connection failed
cycle-test-all.pd 7 2 1 5 (canvas->canvas) connection failed
cycle-test-all.pd 7 2 10 5 (canvas->canvas) connection failed
continuous-ramp-melody.pd 4 0 7 5 (bng->canvas) connection failed
continuous-ramp-melody.pd 6 0 7 3 (gatom->canvas) connection failed
continuous-ramp-melody.pd 7 1 8 0 (canvas->trigger) connection failed
continuous-ramp-melody.pd 9 0 7 2 (float->canvas) connection failed
cycle-drums.pd 23 2 20 5 (canvas->canvas) connection failed
```

They all have to do with connection to a canvas so they’re probably about displaying something. Doesn’t sound like they prevent those patches from having the expected results. Might still be useful to solve them, as these Examples are quite useful and inspiring.

**Comment by algomusic** [comment]
This also happens in Pd vanilla - odd. Fixed by resaving the examples.

**Comment by Enkerli** [comment]
Thanks! The resaved patches do work as expected. Thanks a lot for that!
