### ISSUE TITLE
Possible to add labels to inlets and outlets?

### ISSUE THREAD

**Issue by ribponce** [algomusic/Live-Coding-Toolkit-for-Pure-Data#3]
Hello, thanks so much for the effort on this toolkit, I'm just starting to scratch the surface and learning PD as I go, it's really helpful to study your patches!
I would like to ask if it would be possible to include inlets and outlets labels on the patches, that would be really helpful for checking quickly what sort of input the node expects without having to open the help file.

![image](https://github.com/user-attachments/assets/2885387f-b81b-40bc-82a1-f2ab9e906c44)

I could volunteer to do it myself but I'm sure there will be some patches I'm not gonna understand fully at a first. 
Thank you!

edit: I notice now I was just unlucky to find the 'rand' example without them. Others such as tempo already have this, so it might not be too relevant.

**Comment by algomusic** [comment]
I agree labels would assist readability of patches. I'm not aware of an elegant method for doing this in Pd, beyond checking the help patches that include inlet and outlet info., but I am happy to take advice. Adding free-floating text descriptions does not seem like a sustainable solution.
